/**
 * AI-use disclosure, guardrail 8.
 *
 * The honesty chain runs the length of the project, so the disclosure appears on
 * three surfaces:
 *
 *   (a) The app's own terms. The researcher consents to how the tool uses their
 *       inputs.
 *   (b) The participant consent forms the tool generates. Participants are told
 *       an AI-assisted system handles their data.
 *   (c) The application itself. The Board is told it was prepared with AI
 *       assistance.
 *
 * PLACEHOLDER WORDING. Every string below is a first draft for Shakara to
 * replace. She knows what a Board expects to see and this tool does not. What is
 * not placeholder is the mechanism: surface (c) is generated from what was
 * actually drafted, so it cannot drift from the truth.
 *
 * That last point is the whole reason `drafts.ai_generated` is `not null`. A
 * disclosure that says "parts of this were AI-assisted" when nothing was, or
 * stays silent when something was, is worse than none: it teaches a Board that
 * the disclosure carries no information.
 */

export const DISCLOSURE_VERSION = 'placeholder-2026-08'

/** Surface (a). Shown in the app, before the researcher's inputs are used. */
export const APP_TERMS_DISCLOSURE = `
Research Ethics Board Assistant uses an AI model to help draft parts of your application and to
point out what may be missing.

What that means in practice:

- What you type here is sent to an AI model operated by Anthropic, in order to produce draft text
  and suggestions. Those requests are processed outside Canada.
- Before anything is sent, it passes through an automatic check that removes contact details and
  refuses to send identifiable personal information such as health numbers or dates of birth.
- You are asked not to enter any participant's name, contact details or identifiers anywhere in
  this tool. It is not designed to hold them and does not store them.
- Every draft it produces is recorded as AI-assisted, so your final application can say so
  accurately.
- Nothing is submitted anywhere on your behalf. The tool does not decide whether your research is
  approved. Your Research Ethics Board does that.

This wording is a placeholder pending review.
`.trim()

/** Surface (b). Inserted into generated participant consent forms. */
export const PARTICIPANT_CONSENT_DISCLOSURE = `
How this document was prepared: parts of this consent form and of the research ethics application
behind it were drafted with the help of an artificial intelligence system, reviewed and edited by
the research team before you received it. The research team is responsible for its content.

Your own information is not given to that system. Information that could identify you is not
entered into it, and it is not used to make any decision about you.

This wording is a placeholder pending review.
`.trim()

export interface DisclosureFacts {
  /** Form sections whose text was produced with model assistance. */
  aiAssistedSections: string[]
  /** Sections deliberately not drafted by the tool, per guardrail 4. */
  routedSections: string[]
  modelVersion?: string
}

/**
 * Surface (c). Written from what actually happened, not from a template with a
 * hopeful sentence in it.
 */
export function boardDisclosure(facts: DisclosureFacts): string {
  const lines: string[] = [
    'Disclosure of artificial intelligence assistance',
    '',
  ]

  if (facts.aiAssistedSections.length === 0) {
    lines.push(
      'This application was prepared using Research Ethics Board Assistant, a drafting tool. ' +
        'At the time this document was produced, no section of it had been generated by an ' +
        'artificial intelligence model. The content below is as entered by the research team.',
    )
  } else {
    lines.push(
      'This application was prepared with the assistance of Research Ethics Board Assistant, ' +
        'which uses an artificial intelligence model to produce draft text from information ' +
        'supplied by the research team.',
      '',
      `Sections drafted with AI assistance: ${facts.aiAssistedSections.join(', ')}.`,
      '',
      'All AI-assisted text was reviewed by the research team, which is responsible for the ' +
        'accuracy and completeness of this application. The research team confirmed the tool’s ' +
        'reading of the methodology before any drafting took place.',
    )

    if (facts.modelVersion) {
      lines.push('', `Model used: ${facts.modelVersion}.`)
    }
  }

  if (facts.routedSections.length > 0) {
    lines.push(
      '',
      `The following sections were deliberately not drafted by the tool and were prepared by the ` +
        `research team directly: ${facts.routedSections.join(', ')}. ` +
        'Research involving Indigenous Peoples and community-engaged research are excluded from ' +
        'automated drafting.',
    )
  }

  lines.push(
    '',
    'No participant-identifying information was entered into or stored by the tool.',
    '',
    '[This disclosure wording is a placeholder pending review by the research ethics team.]',
  )

  return lines.join('\n')
}
